config/routes.rb
Rails.application.routes.draw do
  
 devise_for :users, controllers: {
  sessions: 'users/sessions',
  passwords: 'users/passwords',
  registrations: 'users/registrations',
  confirmations: 'users/confirmations'
}

  root to: 'home#index'
  # resources :settings, only: [:index] do
  #   collection do
  #     get :password
  #     patch :update_user
  #     patch :update_password
  #   end
  # end

  # resources :addresses

  namespace :admin do
    root 'home#index', as: :authenticated_root
    
    resources :categories
    resources :products
  end

end

app/views/layouts/admin/_footer.html.erb
<footer class="sticky-footer bg-white">
	<div class="container my-auto">
		<div class="copyright text-center my-auto">
			<span>Copyright &copy; E-Commerce <script>document.write(new Date().getFullYear());</script></span>
		</div>
	</div>
</footer>

app/views/layouts/admin/_nav.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.name %></span>
                    <img class="img-profile rounded-circle" src="/assets/undraw_profile.svg">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <%= link_to admin_authenticated_root_path, class: "dropdown-item" do%>
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Perfil
                <% end -%>
                <div class="dropdown-divider"></div>
                <%= link_to destroy_user_session_path, method: :get, class: "dropdown-item" do %>
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Sair
                <% end -%>
                <!-- <a class="" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a> -->
            </div>
        </li>

    </ul>

</nav>

app/views/layouts/admin/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
   <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= admin_authenticated_root_path %>">
      <div class="sidebar-brand-icon rotate-n-15">
         <i class="fas fa-laugh-wink"></i>
      </div>
      <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
   </a>
   <hr class="sidebar-divider my-0">
   <li class="nav-item <%= controller_name=="home" ? 'active' : '' %>">
      <%= link_to admin_authenticated_root_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span>
      <% end -%>
   </li>
   <hr class="sidebar-divider">
   <li class="nav-item <%= controller_name=="categories" ? 'active' : '' %>">
      <%= link_to admin_categories_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-cog"></i>
      <span>Categoria</span>
      <% end -%>
   </li>
   <hr class="sidebar-divider my-0">
   <li class="nav-item <%= controller_name=="products" ? 'active' : '' %>">
      <%= link_to admin_products_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-shopping-bag"></i>
      <span>Produtos</span>
      <% end -%>
   </li>
      <hr class="sidebar-divider d-none d-md-block">

   <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
   </div>
</ul>