config/routes.rb
Rails.application.routes.draw do
  
 devise_for :users, controllers: {
  sessions: 'users/sessions',
  passwords: 'users/passwords',
  registrations: 'users/registrations',
  confirmations: 'users/confirmations'
}

  root to: 'home#index'
  # resources :settings, only: [:index] do
  #   collection do
  #     get :password
  #     patch :update_user
  #     patch :update_password
  #   end
  # end

  # resources :addresses

  namespace :admin do
    root 'home#index', as: :authenticated_root
    
    resources :categories
    resources :products
  end

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :position, presence: true

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_category_path(@category), notice: "A Categoria foi criado com sucesso." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_category_path(@category), notice: "A Categoria foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_path, notice: "A Categoria foi excluído com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :position)
    end
end

app/views/admin/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= category.position %>
  </p>

</div>

app/views/admin/categories/_form.html.erb
<div class="card">
  <div class="card-content">
    <div class="card-body">
      <%= simple_form_for([:admin, @category]) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :position %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, 'Salvar', class: 'btn btn-info' %>
        <%= link_to "Cancelar", admin_categories_path, class: 'btn btn-danger' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<%= render "form", category: @category %>

app/views/admin/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="h3 mb-4 text-gray-800">Categoria</h1>
<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body table-responsive">
        <table class="table table-striped">
          <thead>
            <th>Nome</th>
            <th>Posição</th>
            <th>Ações</th>
          </thead>
          <tbody>
            <% @categories.each do |category| %>
              <tr>
                  <td><%= category.name %></td>
                  <td><%= category.position %></td>
                  <td>
                    <%= link_to "Detalhes", admin_category_path(category), class: 'btn btn-info' %>
                    <%= link_to "Editar", edit_admin_category_path(category), data: { controller: 'admin-modal' }, class: 'btn btn-warning' %>
                    <%= link_to "Excluir", admin_category_path(category), method: :delete, class: 'btn btn-danger', data: {turbo_method: :delete, turbo_confirm: 'Deseja realmente exlcuir?'} %>
                  </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <%= link_to "Nova categoria", new_admin_category_path, data: { controller: 'admin-modal' }, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<%= render "form", category: @category %>

app/views/admin/categories/show.html.erb
<h1 class="h3 mb-4 text-gray-800">Detalhes da categoria</h1>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <%= render @category %>
      </div>
    </div>
    <%= link_to "Lista", admin_categories_path, class: 'btn btn-success' %>
  </div>
</div>