config/routes.rb
Rails.application.routes.draw do
  
 devise_for :users, controllers: {
  sessions: 'users/sessions',
  passwords: 'users/passwords',
  registrations: 'users/registrations',
  confirmations: 'users/confirmations'
}

  root to: 'home#index'
  # resources :settings, only: [:index] do
  #   collection do
  #     get :password
  #     patch :update_user
  #     patch :update_password
  #   end
  # end

  # resources :addresses

  namespace :admin do
    root 'home#index', as: :authenticated_root
    
    resources :categories
    resources :products
  end

end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category

	validates :name, :description, :price, presence: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
    before_action :set_product, only: %i[show edit update destroy]

    def index
      @products = Product.all
    end

    def edit; end

    def new
      @product = Product.new
      # flash[:notice] = 'Você só pode cadastrar um produto se tiver uma categoria criada.'
      # redirect_to action: :index
    end

    def show; end

    def create
      @product = Product.new(product_params)

      if @product.save
        redirect_to admin_products_path(@product), notice: 'Product criado com sucesso.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @product.update(product_params)
        redirect_to admin_products_path(@product), notice: 'Produto criado com sucesso.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @product.destroy

      respond_to do |format|
        format.html { redirect_to admin_products_path, notice: 'Produto excluída com sucesso.' }
      end
    end

    private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :publish, :category_id)
    end
  end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<div class="card">
	<div class="card-content">
		<div class="card-body">
			<%= simple_form_for([:admin, @product]) do |f| %>
			<%= f.error_notification %>
			<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

			<div class="form-inputs">
				<%= f.input :name %>
				<%#= f.input :image %>
				<%= f.input :description %>
				<%= f.input :price %>
				<%= f.input :publish, style: "height: 30px; width: 50px;" %>
				<%#= f.input :promo %>
				<%#= f.input :promo_price %>
				<%= f.association :category, include_blank: false, input_html: { class: "form-control form-select"},  include_blank: "Selecione uma categoria" %>
			</div>

			<div class="form-actions">
				<%= f.button :submit, 'Salvar', class: 'btn btn-info' %>
				<%= link_to "Cancelar", admin_products_path, class: 'btn btn-danger' %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

<!--   <p>
    <strong>Imagem:</strong>
    <%#= image_tag product.image.variant(:thumb) %>
  </p> -->

  <p>
    <strong>Descrição:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Preço:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Ativo:</strong>
    <%= product.publish %>
  </p>

</div>

app/views/admin/products/edit.html.erb
<%= render "form", product: @product %>

app/views/admin/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="h3 mb-4 text-gray-800">Produtos</h1>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body table-responsive">
        <table class="table table-striped ">
          <thead>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th>Ativo</th>
            <th>Ações</th>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr>
                  <td><%= product.name %></td>
                  <td><%= product.description %></td>
                  <td><%= product.price %></td>
                  <td><%= product.publish %></td>
                  <td>
                    <%= link_to "Detalhes", admin_product_path(product), class: 'btn btn-dark' %>
                    <%= link_to "Editar", edit_admin_product_path(product), data: { controller: 'admin-modal' }, class: 'btn btn-warning' %>
                    <%= link_to "Excluir", admin_product_path(product), method: :delete, class: 'btn btn-danger', data: {turbo_method: :delete, turbo_confirm: 'Deseja realmente exlcuir?'} %>
                  </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <%= link_to "Novo produto", new_admin_product_path, data: { controller: 'admin-modal' }, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<%= render "form", product: @product %>

app/views/admin/products/show.html.erb
<h1 class="h3 mb-4 text-gray-800">Detalhes da categoria</h1>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <%= render @product %>
      </div>
    </div>
  </div>
</div>